[workspace]
resolver = "2"
members = [
    "crates/blog-api",
    "crates/blog-bin",
    "crates/blog-core",
    "crates/blog-domain",
    "crates/blog-infrastructure",
]

[profile.release]
debug = true
