[package]
name = "core"
version = "0.1.0"
authors = ["蜂蜜実験室 <hachimi-lab@outlook.com>"]
edition = "2021"
license = "MIT"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
